-- ============================================================
-- SPORTS EVENT MANAGEMENT SYSTEM — TRIGGERS
-- ============================================================

CREATE OR REPLACE FUNCTION trg_auto_insert_result()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_loser_id INT;
BEGIN
    IF OLD.WinnerID IS NOT NULL OR NEW.WinnerID IS NULL THEN
        RETURN NEW;
    END IF;

    IF NEW.WinnerID = NEW.Team1ID THEN
        v_loser_id := NEW.Team2ID;
    ELSIF NEW.WinnerID = NEW.Team2ID THEN
        v_loser_id := NEW.Team1ID;
    ELSE
        RAISE EXCEPTION 'WinnerID % is neither Team1 nor Team2.', NEW.WinnerID;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM Result WHERE MatchID = NEW.MatchID) THEN
        INSERT INTO Result (MatchID, WinnerID, LoserID, Remarks)
        VALUES (NEW.MatchID, NEW.WinnerID, v_loser_id,
                'Auto-generated by trigger');
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_match_winner_update ON Match;

CREATE TRIGGER trg_match_winner_update
    AFTER UPDATE OF WinnerID ON Match
    FOR EACH ROW
    EXECUTE FUNCTION trg_auto_insert_result();
